fix CSS composants + animation text
WildCodeSchool/2023-09-JS-Lille-blue-project-2-groupe2-stix pull request #17
Opened 2023-11-07 16:14 UTC by Marie-Sail

2023-11-07 16:23 UTC, VincentRssx approved these changes

2023-11-08 10:40 UTC, fantinerudent requested changes

2023-11-08 10:40 UTC, fantinerudent commented on frontend/src/components/homeText/homeText.jsx
> +        Les planète
planèteS

2023-11-08 10:46 UTC, fantinerudent approved these changes

2023-11-08 10:47 UTC, merged