création de la navbar
WildCodeSchool/2023-09-JS-Lille-blue-project-2-groupe2-stix pull request #7
Opened 2023-10-26 14:49 UTC by Farid-Zian

2023-10-26 15:06 UTC, Marie-Sail requested changes

2023-10-26 15:06 UTC, Marie-Sail commented on frontend/src/components/Navbar.jsx
> +    <nav className="navbar carrousel">
ne met pas d'espace dans le nom de ta class

2023-10-26 15:06 UTC, Marie-Sail commented on frontend/src/components/Navbar.jsx
> +            className="planete terre"
revoir le nom de la class

2023-10-26 15:06 UTC, Marie-Sail commented on frontend/src/components/Navbar.jsx
> +            className="planete mars"
revoir le nom de la class

2023-10-26 15:06 UTC, Marie-Sail commented on frontend/src/components/Navbar.jsx
> +            className="planete uranus"
revoir le nom de la class

2023-10-27 09:13 UTC, Marie-Sail requested changes

2023-10-27 10:04 UTC, Marie-Sail approved these changes

2023-10-30 08:29 UTC, Sax593 requested changes

2023-10-30 08:29 UTC, Sax593 commented on frontend/src/components/Navbar.jsx
> +      <div className="planetes">
className in english please

2023-10-30 08:29 UTC, Sax593 commented on frontend/src/components/Navbar.jsx
> +        <div className="planete">
className in english please

2023-10-30 08:29 UTC, Sax593 commented on frontend/src/components/Navbar.jsx
> +            className="soleil"
className in english please

2023-10-30 08:29 UTC, Sax593 commented on frontend/src/components/Navbar.jsx
> +        <div className="planete">
className in english please

2023-10-30 08:29 UTC, Sax593 commented on frontend/src/components/Navbar.jsx
> +        <div className="planete">
className in english please

2023-10-30 08:29 UTC, Sax593 commented on frontend/src/components/Navbar.jsx
> +            className="planete-img"
className in english please

2023-10-30 08:29 UTC, Sax593 commented on frontend/src/components/Navbar.jsx
> +        <div className="planete">
className in english please

2023-10-30 08:29 UTC, Sax593 commented on frontend/src/components/Navbar.scss
> +.planetes {
className in english please

2023-10-30 08:29 UTC, Sax593 commented on frontend/src/components/Navbar.scss
> +  transition: box-shadow 0.3s ease;
why not put it on line 28

2023-10-30 13:38 UTC, NemoOnTheNet approved these changes

2023-10-31 14:29 UTC, Sax593 approved these changes

2023-11-06 15:57 UTC, NemoOnTheNet commented on frontend/src/components/navbar/Navbar.jsx
> +
Il faut enlever les commentaires

2023-11-06 15:57 UTC, NemoOnTheNet commented on frontend/src/components/navbar/logo.scss
Il faut mettre les fichiers logo dans un dossier à part

2023-11-06 15:57 UTC, NemoOnTheNet commented on frontend/src/pages/home.jsx
> +import ImageCall from "../components/image-call";
il faut supprimer ce qui n'existe plus

2023-11-07 15:39 UTC, closed without merging