intégration scss text
WildCodeSchool/2023-09-JS-Lille-blue-project-2-groupe2-stix pull request #8
Opened 2023-10-27 13:29 UTC by Marie-Sail

2023-10-27 13:59 UTC, NemoOnTheNet approved these changes

2023-10-30 08:01 UTC, Sax593 requested changes

2023-10-30 08:01 UTC, Sax593 commented on frontend/src/components/homeText.jsx
> +      <p className="text1">
className bad naming

2023-10-30 08:01 UTC, Sax593 commented on frontend/src/components/homeText.jsx
> +      <p className="text2">
className bad naming

2023-10-30 08:01 UTC, Sax593 commented on frontend/src/components/homeText.jsx
> +      <p className="text3">
className bad naming

2023-10-30 08:01 UTC, Sax593 commented on frontend/src/components/homeText.jsx
> +      <p className="text4">
className bad naming

2023-10-30 16:00 UTC, NemoOnTheNet approved these changes

2023-10-31 09:26 UTC, Sax593 approved these changes

2023-10-31 10:13 UTC, merged